map:
  map_width: 820
  map_height: 500

platforms:
  - {x: 0, y: 200, width: 200, height: 16}
  - {x: 40, y: 420, width: 600, height: 16}
  - {x: 580, y: 140, width: 200, height: 16}
  - {x: 600, y: 350, width: 400, height: 16}
  - {x: 0, y: 600, width: 800, height: 16}

invalid_positions:
  - {x: 0, y: 430, width: 820, height: 2}

boxes:
  - {x: 100, y: 100}
  - {x: 180, y: 100}
  - {x: 200, y: 300}

weapons:
  - {x: 30, y: 180}
  - {x: 30, y: 300}
  - {x: 400, y: 250}
  - {x: 600, y: 100}

ducks:
  - {x: 120, y: 340}
  - {x: 300, y: 210}
  - {x: 500, y: 120}
  - {x: 700, y: 90}