game:
  title: "Duck Game"

# The speed of the duck in pixels for diferent actions
ducks_config:
  health: 20
  tiles_per_jump: 200 # The number of tiles the duck moves when jumping
  product_factor_jump: 2 # speed of the duck when jumping
  add_factor_jump: 3 # linear speed of the duck when jumping
  product_factor_gravity: 2 # speed of the duck when falling
  add_factor_gravity: 8 # linear speed of the duck when falling
  speed_of_game: 10 # speed of the duck when moving

weapon:
  grenade:
    shot: 1
    damage: 35
    recoil: 0
    scope: 7 # distnace of the explosion in tiles
    reload_time: 1500 # time to explode
    hitbox_width: 25
    hitbox_height: 25

  banana:
    shot: 1
    damage: 10
    recoil: 0 # no recoil
    scope: 0 # no scope
    reload_time: 0 # never explodes
    hitbox_width: 25
    hitbox_height: 25

  pew_pew_laser:
    shot: 100000
    damage: 8
    recoil: 0
    scope: 35 # distnace of shot in tiles
    reload_time: 20 #time between shots
    hitbox_width: 36
    hitbox_height: 26

  laser_rifle:
    shot: 100000
    damage: 15
    recoil: 0
    scope: 62 # distnace of shot in tiles
    reload_time: 5 #time between shots
    hitbox_width: 48
    hitbox_height: 24

  ak_47:
    shot: 100000
    damage: 20  
    recoil: 10
    scope: 32 # distnace of shot in tiles
    reload_time: 5 #time between shots
    hitbox_width: 48
    hitbox_height: 24

  dueling_pistol:
    shot: 100000
    damage: 50
    recoil: 200
    scope: 25 # distnace of shot in tiles
    reload_time: 20 #time between shots
    hitbox_width: 52
    hitbox_height: 26

  cowboy_pistol:
    shot: 100000
    damage: 5
    recoil: 0
    scope: 25  # distnace of shot in tiles
    reload_time: 20 #time between shots
    hitbox_width: 36
    hitbox_height: 18

  magnum:
    shot: 100000
    damage: 7
    recoil: 30
    scope: 30 # distnace of shot in tiles
    reload_time: 20 #time between shots
    hitbox_width: 52
    hitbox_height: 26

  shotgun:
    shot: 100000
    damage: 17
    recoil: 80
    scope: 8 # distnace of shot in tiles
    reload_time: 10 #time after recharge
    hitbox_width: 36
    hitbox_height: 18

  sniper:
    shot: 100000
    damage: 50
    recoil: 0
    scope: 100 # distnace of shot in tiles
    reload_time: 10 #time after recharge
    hitbox_width: 33
    hitbox_height: 9
